### ISSUE TITLE
Wrong filename - remove_unsupported_libraries.rb

### ISSUE THREAD

**Issue by zsombornagy** [fermoya/CatalystPodSupport#1]
The "How can I use it?" shows to import `remove_unsupported_libraries.rb`, but the linked file is actually called `remove_ios_only_frameworks.rb`

**Comment by fermoya** [comment]
You're right, I totally missed that one. I updated the README, thanks.
<img width="362" alt="Screenshot 2020-06-15 at 16 08 39" src="https://user-images.githubusercontent.com/11335612/84674139-80a0eb80-af22-11ea-859d-953cc3df5f05.png">
