### ISSUE TITLE
[BUG]  Unknown command: `catalyst`

### ISSUE THREAD

**Issue by Howard-Flipped** [fermoya/CatalystPodSupport#42]
**Describe the bug**

My cocoapods install with brew, in use cocoapods-catalyst-support,
when input: pod catalyst run, error: 

pod catalyst run
[!] Unknown command: `catalyst`
Did you mean: list?

**Podfile**
Please provide your `Podfile` here.

**Environment**
* `cocoapods-catalyst-support` => <run `gem list | grep cocoapods-catalyst-support`>
*  ✅ cocoapods-catalyst-support (0.2.1)
* _Ruby_ version [e.g 2.6.0] => <run `ruby --version`>
*  ✅ ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
* _Cocoapods_ version [e.g 1.10.0] => <run `pod --version`>
*  ✅ 1.11.3
* _Xcode_ version [e.g 12.2] => <run `xcodebuild -version`>
*  ✅ Xcode 13.3.1 Build version 13E500a

**Additional context**

**Comment by Howard-Flipped** [comment]
<img width="645" alt="截屏2022-04-18 16 34 02" src="https://user-images.githubusercontent.com/15625147/163781329-f576c01d-4906-46e7-b690-3213eecdf2a4.png">

**Comment by fermoya** [comment]
@Howard-Wang-Hao have you followed the [Installation](https://github.com/fermoya/cocoapods-catalyst-support#installation) guide? I’d recommend you use `Bundle` and a `Gemfile` in your project. Home brew is not currently supported, see request [here](https://github.com/fermoya/cocoapods-catalyst-support/issues/21)

**Comment by Howard-Flipped** [comment]
Hello, I have followed your Installation & Usage guide.
But there are still errors,
Libraries that don't support Macs don't seem to be ruled out


pod catalyst run
Analyzing dependencies
Downloading dependencies
Generating Pods project

#### Configuring macos dependencies ####

#### Unsupported Libraries ####
[]

#### Unsupported dependencies ####
[]

#### Frameworks not to be included in the Archive ####
[]

#### Resources not to be included in the Archive ####
[]

#### Flagging unsupported libraries ####
	Target: Alamofire
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliHACore
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliHALogEngine
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliHAMethodTrace
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliHAProtocol
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliHASecurity
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliRemoteDebugInterface
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AlicloudHAUtil
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AlicloudSettingService
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AlicloudTLog
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AlicloudUTDID
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AlicloudUtils
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: AliyunOSSiOS
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: CryptoSwift
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: DeviceKit
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: EMASRest
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: FileKit
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: HiPosPrinter
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: IQKeyboardManagerSwift
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Kingfisher
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: MJRefresh
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: MKProgress
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: MagicalRecord
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Moya
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: ObjcExceptionBridging
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: ProgressHUD
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: RemoteDebugChannel
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SPPermissions
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SSZipArchive
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SnapKit
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Starscream
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SwiftProtobuf
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SwiftyGif
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: SwiftyJSON
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: TBJSONModel
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: TBRest
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: TRemoteDebugger
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: UMAPM
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: UMCCommonLog
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: UMCommon
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: UMDevice
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: UMPush
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: XCGLogger
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: ZipArchive
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Pods-HiPOSHD_iPad
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Pods-HiPOSHD_iPad-HiPOSHD_iPadUITests
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag
	Target: Pods-HiPOSHD_iPadTests
		Scheme: Dev_Debug
			Nothing to flag
		Scheme: Rel_Debug
			Nothing to flag
		Scheme: Qa_Debug
			Nothing to flag
		Scheme: Rel_Release
			Nothing to flag
		Scheme: Dev_Release
			Nothing to flag
		Scheme: Qa_Release
			Nothing to flag

#### Filtering build phases ####

#### Filtering dependencies ####

#### Changing frameworks and resources script ####
	Target: Pods-HiPOSHD_iPad
		-Uninstalling frameworks
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
		-Uninstalling resources
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
	Target: Pods-HiPOSHD_iPad-HiPOSHD_iPadUITests
		-Uninstalling frameworks
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
		-Uninstalling resources
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
	Target: Pods-HiPOSHD_iPadTests
		-Uninstalling frameworks
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
		-Uninstalling resources
			Uninstalling for configurations: ["Release", "Debug", "Dev_Debug", "Rel_Debug", "Qa_Debug", "Rel_Release", "Dev_Release", "Qa_Release"]
			Nothing to uninstall
Catalyst => Done! Your Catalyst dependencies are ready to go
Integrating client project
Pod installation complete! There are 29 dependencies from the Podfile and 44 total pods installed.

**Comment by Howard-Wang-Hao** [comment]
<img width="1315" alt="截屏2022-04-18 18 47 00" src="https://user-images.githubusercontent.com/15625147/163798654-06af962d-3544-4fd4-984d-cd1e2167bddb.png">
<img width="1315" alt="截屏2022-04-18 18 47 00" src="https://user-images.githubusercontent.com/15625147/163798675-0b421152-7b4d-4589-9fae-2fa0d88b5d3b.png">

**Comment by Howard-Flipped** [comment]
<img width="1315" alt="截屏2022-04-18 18 47 00" src="https://user-images.githubusercontent.com/15625147/163799239-c33dd2d5-a612-4b1a-8d11-8b6ed0eb77d9.png">
<img width="1329" alt="截屏2022-04-18 18 47 16" src="https://user-images.githubusercontent.com/15625147/163799462-9060dea8-5edf-4078-bc8b-61668e378999.png">

**Comment by Howard-Flipped** [comment]
@fermoya Very confused, it seems that every step before compiling is not reported by mistake

**Comment by fermoya** [comment]
@Howard-Wang-Hao i need your Podfile to make take a look at your dependency structure and how the way you're using the framework

**Comment by Howard-Flipped** [comment]
```
require 'cocoapods-catalyst-support'

source "https://github.com/aliyun/aliyun-specs.git"

source 'https://cdn.cocoapods.org/'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'HiPOSHD_iPad' do
  # Pods for HiPOSHD_iPad
  pod 'Moya'

  pod 'SnapKit'
  pod 'XCGLogger' #, '~> 7.0.1'
  pod 'FileKit'   #, '~> 5.0.0'
  pod 'SSZipArchive'

  pod 'ProgressHUD'
  pod 'MKProgress'

  pod 'Kingfisher'
  pod 'MagicalRecord'
  pod 'SwiftyJSON', '~> 4.0'
  
  pod 'Starscream'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyGif'
  pod 'MJRefresh'
  pod 'SwiftProtobuf', '~> 1.0'
  
  pod 'SPPermissions/Bluetooth'
  pod 'SPPermissions/Location'
  pod 'SPPermissions/Camera'
  pod 'SPPermissions/Notification'
  pod 'SPPermissions/Calendar'

  pod 'UMCommon'
  pod 'UMDevice'

  pod 'UMPush'
  pod 'UMAPM'
  pod 'UMCCommonLog'

  pod 'DeviceKit'
  pod 'CryptoSwift'

  pod 'AlicloudTLog'

  target 'HiPOSHD_iPadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HiPOSHD_iPadUITests' do
    # Pods for testing
  end

end


# Configure your macCatalyst dependencies
catalyst_configuration do
	# Uncomment the next line for a verbose output
  verbose!

  # This dependency will only be available for iOS
  ios ['UMCommon', 'UMDevice', 'UMPush', 'UMAPM', 'UMCCommonLog', 'AlicloudTLog']

  # This dependency will only be available for macOS
#	macos []
end

# Configure your macCatalyst dependencies
post_install do |installer|
  installer.configure_catalyst
end
```

**Comment by Howard-Flipped** [comment]
@fermoya it is here, note that AlicloudTLog depends on AliHACore

**Comment by Howard-Flipped** [comment]
@fermoya Is there any problem？

**Comment by ahmdmhasn** [comment]
Since it's not supported on Homebrew yet #21,  you should use gem.
- In Gemfile
- Add `gem 'cocoapods-catalyst-support'`
